PROGRAM GNSS_ARR
IMPLICIT NONE

CHARACTER (LEN=255) :: cwd
CHARACTER (LEN=255) :: INPUT_PATH
CHARACTER (LEN=255) :: OUTPUT_PATH
CHARACTER (LEN=20) :: IFN
CHARACTER (LEN=30) :: OFN
CHARACTER (LEN=10) :: FMT

INTEGER, PARAMETER :: ROWS = 537
INTEGER, PARAMETER :: COL = 4
INTEGER :: I, J

REAL*8, DIMENSION(ROWS,COL) :: ELE_MTX
!REAL*8, DIMENSION(COL,ROWS) :: ELE_MTX

CALL getcwd(cwd)
!WRITE(*,*) TRIM(cwd)
IFN = "/elevation.txt"
OFN = "/elevation_fortran.txt"
!FN2 = TRIM(FN)

INPUT_PATH=TRIM(cwd)//IFN
PRINT *, "INPUT_PATH=",INPUT_PATH
OUTPUT_PATH=TRIM(cwd)//OFN
PRINT *, "OUTPUT_PATH=",OUTPUT_PATH


!OPEN(UNIT=10, FILE=INPUT_PATH, ACCESS='STREAM',STATUS='OLD', ACTION='READ')
!OPEN(UNIT=20, FILE=OUTPUT_PATH, ACCESS='STREAM',STATUS='REPLACE', ACTION='WRITE')

OPEN(UNIT=10, FILE = INPUT_PATH, FORM='FORMATTED',STATUS='OLD', ACTION='READ')
OPEN(UNIT=20, FILE = OUTPUT_PATH, FORM='FORMATTED', STATUS='REPLACE', ACTION='WRITE')

FMT="(4F9.3)"

!READ(10) ELE_MTX
READ(10,FMT) ELE_MTX



!I=ROWS
!DO J=1,COL
!   WRITE(*,FMT) ELE_MTX(I,J)
!   WRITE(20,FMT) ELE_MTX(I,J)
!END DO 


DO I=1,ROWS
  WRITE(20,FMT) (ELE_MTX(I,J), J=1,COL)
  WRITE(*,FMT) (ELE_MTX(I,J), J=1,COL)
END DO 

!DO I=1,ROWS
!  WRITE(20) (ELE_MTX(I,J), J=1,COL)
!  WRITE(*,*) (ELE_MTX(I,J), I=1,2)
!END DO 



END PROGRAM GNSS_ARR
