PROGRAM GNSS_correction

USE MD_BASIC

IMPLICIT NONE

!=============OPEN================
CHARACTER (LEN=255) :: cwd
CHARACTER (LEN=255) :: COMMON_PATH
CHARACTER (LEN=255) :: INPUT_PATH
CHARACTER (LEN=255) :: INPUT_PATH2
CHARACTER (LEN=255) :: OUTPUT_PATH
CHARACTER (LEN=255) :: OUTPUT_PATH2
CHARACTER (LEN=50) :: IFN
CHARACTER (LEN=30) :: IFN2
CHARACTER (LEN=30) :: OFN
CHARACTER (LEN=30) :: OFN2
CHARACTER (LEN=10) :: FMT
!=================================

!==============MALA==============
INTEGER, PARAMETER :: DIS = 1498
INTEGER, PARAMETER :: TRA = 103
INTEGER, PARAMETER :: ROWS = 616
!
!INTEGER, PARAMETER :: ROWS = 512
!INTEGER, PARAMETER :: ROWS = 503
INTEGER, DIMENSION(TRA,DIS) :: ROWS2
INTEGER :: MAX_ROWS2, MAX_SHIFT
!================================

!=====================DATA========================
!INTEGER, DIMENSION(TRA,DIS) :: Shift_GPRelev
INTEGER, DIMENSION(DIS,TRA) :: Shift_GPRelev


INTEGER, DIMENSION(TRA,DIS) :: Shift_GPRelev2
INTEGER, DIMENSION(TRA,DIS) :: Shift_GPRelev_FLIP

REAL*8, DIMENSION(DIS,TRA,ROWS) :: BSCAN_IMAGE_GC
REAL*8, DIMENSION(DIS,TRA,ROWS) :: BSCAN_GC_FLIP
REAL*8, DIMENSION(:,:,:), ALLOCATABLE :: BSCAN_GC_GNC
REAL*8, DIMENSION(:,:,:), ALLOCATABLE :: BSCAN_GC_GNC2
REAL*8, DIMENSION(:,:,:), ALLOCATABLE :: BSCAN_GC_GNC3
REAL*8, DIMENSION(:,:,:), ALLOCATABLE :: BSCAN_GC_GNC4
!=================================================

INTEGER :: I, J, X, Y, Z
INTEGER :: CUT_U, CUT_U2, CUT_D, CUT_D2

!====================PATH=========================
CALL getcwd(cwd)
COMMON_PATH = "/home/changwan/GNSS/3D_correction"
IFN = "/3Dmorph_GPR_correction.txt"
!IFN2 = "/BSCAN_GPR_noprocessing.txt"
IFN2 = "/HPF_BSCAN_GC.txt"


OFN = "/GPR_elev.txt"
!OFN2 = "/BSCAN_GC_GNC.txt" !GNSS CORRECTION (GNC)
OFN2 = "/HPF_BSCAN_GC_GNC.txt" !GNSS CORRECTION (GNC)


INPUT_PATH=TRIM(cwd)//IFN
INPUT_PATH2=TRIM(COMMON_PATH)//IFN2
PRINT *, "INPUT_PATH=",INPUT_PATH
PRINT *, "INPUT_PATH2=",INPUT_PATH2

OUTPUT_PATH=TRIM(cwd)//OFN
OUTPUT_PATH2=TRIM(COMMON_PATH)//OFN2
PRINT *, "OUTPUT_PATH=",OUTPUT_PATH
PRINT *, "OUTPUT_PATH2=",OUTPUT_PATH2
!=================================================


OPEN(UNIT=10, FILE = INPUT_PATH, FORM="FORMATTED", STATUS='OLD', ACTION='READ')
!OPEN(UNIT=10, FILE = INPUT_PATH, ACCESS='STREAM', STATUS='OLD', ACTION='READ')
OPEN(UNIT=11, FILE = INPUT_PATH2, FORM="FORMATTED", STATUS='OLD', ACTION='READ')
!OPEN(UNIT=11, FILE = INPUT_PATH2, ACCESS='STREAM', STATUS='OLD', ACTION='READ')
OPEN(UNIT=20, FILE = OUTPUT_PATH, STATUS='REPLACE', ACTION='WRITE')
OPEN(UNIT=21, FILE = OUTPUT_PATH2, STATUS='REPLACE', ACTION='WRITE')

FMT="(I4)"
!READ(10,FMT) Shift_GPRelev
READ(10,*) Shift_GPRelev


READ(11,*) BSCAN_IMAGE_GC


!USE THE FLIPED WHEN EXPLOROED IN A REVERSE WAY
!CALL flip_1D_INTEGER(Shift_GPRelev, DIS, Shift_GPRelev_FLIP)
!CALL flip_2D(BSCAN_IMAGE_GC, DIS, ROWS,BSCAN_GC_FLIP)
!INCLUDE "UP_DOWN.h"
!INCLUDE "DOWN_UP_FLIP.h"
!DO X = 1, DIS
!   WRITE(20,*) Shift_GPRelev_FLIP(X)
!END DO 



!INCLUDE "UP_DOWN.h"
!INCLUDE "DOWN_UP.h"

!DO Y = 1, DIS
!DO X = 1, TRA
!   WRITE(20,*) Shift_GPRelev(X, Y)
!END DO 
!END DO 


!DO Z = 1, MAX_ROWS2
!DO Y = 1, TRA
!   WRITE(21,*) (BSCAN_GC_GNC4(X,Y,Z), X = 1,DIS)
!   WRITE(21,*) (BSCAN_GC_GNC(X,Y,Z), X = 1,DIS)
!END DO 
!END DO

DEALLOCATE(BSCAN_GC_GNC)
DEALLOCATE(BSCAN_GC_GNC2)
DEALLOCATE(BSCAN_GC_GNC3)
DEALLOCATE(BSCAN_GC_GNC4)

END PROGRAM 
